INSERT INTO MUSALA_USERS (username, email, password) VALUES ('tony', 'tony@mail.com', '$2a$10$JYkSR6.NZwRtygD7GiQ2uu2/qcP1RvwvnSd/pT5SYkYCuuN1fTDDe');
INSERT INTO MUSALA_USERS (username, email, password) VALUES ('mailen', 'mailen@mail.com', '$2a$10$wgGrqFroS.aah424sXywQurq1PY6ns3RhadyxQsbbJVmLgPo3r9fa');
INSERT INTO MUSALA_GATEWAYS (ip, name) VALUES ('192.168.1.1', 'gateway1');
INSERT INTO MUSALA_GATEWAYS (ip, name) VALUES ('192.168.1.1', 'gateway2');
INSERT INTO MUSALA_GATEWAYS (ip, name) VALUES ('192.168.1.1', 'gateway3');
INSERT INTO MUSALA_GATEWAYS (ip, name) VALUES ('192.168.1.1', 'gateway4');
INSERT INTO MUSALA_GATEWAYS (ip, name) VALUES ('192.168.1.1', 'gateway5');
INSERT INTO MUSALA_DEVICES (date_created, status, vendor) VALUES ('2022-12-03', true, 'alguien1');
INSERT INTO MUSALA_DEVICES (date_created, status, vendor) VALUES ('2022-12-03', true, 'alguien2');
INSERT INTO MUSALA_DEVICES (date_created, status, vendor) VALUES ('2022-12-03', true, 'alguien3');
INSERT INTO MUSALA_DEVICES (date_created, status, vendor) VALUES ('2022-12-03', true, 'alguien4');
INSERT INTO MUSALA_DEVICES (date_created, status, vendor) VALUES ('2022-12-03', true, 'alguien5');
INSERT INTO MUSALA_DEVICES (date_created, status, vendor) VALUES ('2022-12-03', true, 'alguien6');
INSERT INTO MUSALA_DEVICES (date_created, status, vendor) VALUES ('2022-12-03', true, 'alguien7');
